import { FormEvent, useEffect, useState } from 'react';
import { Link, Navigate, NavLink, Outlet, Route, Routes, useNavigate } from 'react-router';
import { apiRequest, type ApiError } from '../../lib/apiClient';

type Item = Record<string, unknown> & { id: string; version: number; state: string };
type Resource = 'content' | 'schedule' | 'map';
const labels: Record<Resource, string> = { content: 'Content', schedule: 'Schedule', map: 'Map' };

function SessionGuard() {
  const [state, setState] = useState<'loading' | 'allowed' | 'denied'>('loading');
  useEffect(() => { apiRequest('/api/admin/session').then(() => setState('allowed')).catch(() => setState('denied')); }, []);
  if (state === 'loading') return <p role="status">Checking session…</p>;
  return state === 'allowed' ? <Outlet /> : <Navigate to="/admin/login" replace />;
}
export function AdminLogin() {
  const navigate = useNavigate(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { await apiRequest('/api/admin/session', { method: 'POST', body: JSON.stringify({ identifier: form.get('identifier'), password: form.get('password') }) }); navigate('/admin'); } catch { setError('Sign-in failed. Check your credentials and try again.'); } finally { setBusy(false); } }
  return <main className="admin-login"><h1>Administrator sign in</h1><form onSubmit={submit}><label>Identifier<input name="identifier" required minLength={3} autoComplete="username" /></label><label>Password<input name="password" required minLength={12} type="password" autoComplete="current-password" /></label>{error && <p role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</button></form></main>;
}
function AdminShell() { const navigate = useNavigate(); async function logout() { await apiRequest('/api/admin/logout', { method: 'POST' }); navigate('/admin/login'); } return <div className="admin-app"><a className="skip-link" href="#admin-main">Skip to content</a><header className="admin-header"><Link to="/admin">Administration</Link><nav aria-label="Administration"><NavLink to="/admin">Dashboard</NavLink><NavLink to="/admin/content">Content</NavLink><NavLink to="/admin/schedule">Schedule</NavLink><NavLink to="/admin/map">Map</NavLink><button onClick={() => void logout()}>Log out</button></nav></header><main id="admin-main"><Outlet /></main></div>; }
function Dashboard() { const [counts, setCounts] = useState<Record<string, number>>(); useEffect(() => { apiRequest<{ counts: Record<string, number> }>('/api/admin/dashboard').then((v) => setCounts(v.counts)); }, []); return <section className="admin-page"><h1>Dashboard</h1>{!counts ? <p role="status">Loading dashboard…</p> : <ul><li>{counts.content} content items</li><li>{counts.schedule} schedule entries</li><li>{counts.map} map points</li></ul>}</section>; }
function fields(resource: Resource) { return resource === 'content' ? [['contentKey', 'Key'], ['title', 'Title'], ['body', 'Body']] : resource === 'schedule' ? [['title', 'Title'], ['description', 'Description'], ['startsAt', 'Starts at'], ['endsAt', 'Ends at'], ['location', 'Location']] : [['label', 'Label'], ['description', 'Description'], ['latitude', 'Latitude'], ['longitude', 'Longitude']]; }
function ResourcePage({ resource }: { resource: Resource }) { const [items, setItems] = useState<Item[]>(); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const refresh = () => apiRequest<Record<string, Item[]>>(`/api/admin/${resource}`).then((data) => setItems(data[resource === 'map' ? 'points' : 'entries'])); useEffect(() => { void refresh().catch(() => setError('Unable to load this resource.')); }, [resource]); async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const data: Record<string, unknown> = Object.fromEntries(form); if (resource === 'map') { data.latitude = Number(data.latitude); data.longitude = Number(data.longitude); } try { await apiRequest(`/api/admin/${resource}`, { method: 'POST', body: JSON.stringify(data) }); event.currentTarget.reset(); setNotice('Created successfully.'); await refresh(); } catch (e) { setError(message(e)); } } async function action(item: Item, action: 'publish' | 'unpublish' | 'delete') { if (action === 'delete' && !window.confirm('Delete this item? It will no longer be publicly available.')) return; try { await apiRequest(`/api/admin/${resource}/${item.id}${action === 'delete' ? '' : `/${action}`}`, { method: action === 'delete' ? 'DELETE' : 'POST', body: JSON.stringify({ version: item.version }) }); setNotice(action === 'delete' ? 'Deleted successfully.' : 'Updated successfully.'); await refresh(); } catch (e) { setError(message(e)); } }
  return <section className="admin-page"><h1>{labels[resource]}</h1><form className="admin-form" onSubmit={create}><h2>Create item</h2>{fields(resource).map(([name, label]) => <label key={name}>{label}<input name={name} required={name !== 'description' && name !== 'location'} type={name.includes('At') ? 'datetime-local' : name === 'latitude' || name === 'longitude' ? 'number' : 'text'} step={name === 'latitude' || name === 'longitude' ? 'any' : undefined} /></label>)}<button className="button primary">Create</button></form>{notice && <p role="status">{notice}</p>}{error && <p role="alert">{error}</p>}{!items ? <p role="status">Loading items…</p> : items.length === 0 ? <p>No items yet.</p> : <ul className="admin-list">{items.map((item) => <li key={item.id}><strong>{String(item.title ?? item.label ?? item.contentKey)}</strong> <span>{item.state}</span><button onClick={() => void action(item, item.state === 'published' ? 'unpublish' : 'publish')}>{item.state === 'published' ? 'Unpublish' : 'Publish'}</button><button className="danger" onClick={() => void action(item, 'delete')}>Delete</button></li>)}</ul>}</section>;
}
function message(error: unknown) { return (error as ApiError).status === 409 ? 'This item changed elsewhere. Reload and try again.' : 'The request could not be completed.'; }
export function AdminRoutes() { return <Routes><Route path="/admin/login" element={<AdminLogin />} /><Route element={<SessionGuard />}><Route path="/admin" element={<AdminShell />}><Route index element={<Dashboard />} /><Route path="content" element={<ResourcePage resource="content" />} /><Route path="schedule" element={<ResourcePage resource="schedule" />} /><Route path="map" element={<ResourcePage resource="map" />} /></Route></Route></Routes>; }
