import { FormEvent, useEffect, useState } from 'react';
import { Link, Navigate, NavLink, Outlet, Route, Routes, useNavigate } from 'react-router';
import { apiRequest, type ApiError } from '../../lib/apiClient';

type Item = Record<string, unknown> & { id: string; version: number; state: string };
type Resource = 'content' | 'schedule' | 'map';
const labels: Record<Resource, string> = { content: 'Contenido', schedule: 'Cronograma', map: 'Mapa' };

function SessionGuard() {
  const [state, setState] = useState<'loading' | 'allowed' | 'denied'>('loading');
  useEffect(() => { apiRequest('/api/admin/session').then(() => setState('allowed')).catch(() => setState('denied')); }, []);
  if (state === 'loading') return <p role="status">Verificando sesión…</p>;
  return state === 'allowed' ? <Outlet /> : <Navigate to="/admin/login" replace />;
}
export function AdminLogin() {
  const navigate = useNavigate(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { await apiRequest('/api/admin/session', { method: 'POST', body: JSON.stringify({ identifier: form.get('identifier'), password: form.get('password') }) }); navigate('/admin'); } catch { setError('No se pudo iniciar sesión. Verifique sus credenciales e intente nuevamente.'); } finally { setBusy(false); } }
  return <main className="admin-login"><h1>Inicio de sesión de administrador</h1><form onSubmit={submit}><label>Identificador<input name="identifier" required minLength={3} autoComplete="username" /></label><label>Contraseña<input name="password" required minLength={12} type="password" autoComplete="current-password" /></label>{error && <p role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy ? 'Iniciando sesión…' : 'Iniciar sesión'}</button></form></main>;
}
function AdminShell() { const navigate = useNavigate(); async function logout() { await apiRequest('/api/admin/logout', { method: 'POST' }); navigate('/admin/login'); } return <div className="admin-app"><a className="skip-link" href="#admin-main">Ir al contenido principal</a><header className="admin-header"><Link to="/admin">Administración</Link><nav aria-label="Administración"><NavLink to="/admin">Panel de control</NavLink><NavLink to="/admin/content">Contenido</NavLink><NavLink to="/admin/schedule">Cronograma</NavLink><NavLink to="/admin/map">Mapa</NavLink><NavLink to="/admin/participants">Participantes</NavLink><NavLink to="/admin/campaigns">Campañas</NavLink><button onClick={() => void logout()}>Cerrar sesión</button></nav></header><main id="admin-main"><Outlet /></main></div>; }
function Dashboard() { const [counts, setCounts] = useState<Record<string, number>>(); useEffect(() => { apiRequest<{ counts: Record<string, number> }>('/api/admin/dashboard').then((v) => setCounts(v.counts)); }, []); return <section className="admin-page"><h1>Panel de control</h1>{!counts ? <p role="status">Cargando panel de control…</p> : <ul><li>{counts.content} elementos de contenido</li><li>{counts.schedule} entradas de cronograma</li><li>{counts.map} puntos del mapa</li></ul>}</section>; }
function fields(resource: Resource) { return resource === 'content' ? [['contentKey', 'Clave'], ['title', 'Título'], ['body', 'Contenido']] : resource === 'schedule' ? [['title', 'Título'], ['description', 'Descripción'], ['startsAt', 'Comienza en'], ['endsAt', 'Termina en'], ['location', 'Ubicación']] : [['label', 'Etiqueta'], ['description', 'Descripción'], ['latitude', 'Latitud'], ['longitude', 'Longitud']]; }
function ResourcePage({ resource }: { resource: Resource }) { const [items, setItems] = useState<Item[]>(); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const refresh = () => apiRequest<Record<string, Item[]>>(`/api/admin/${resource}`).then((data) => setItems(data[resource === 'map' ? 'points' : 'entries'])); useEffect(() => { void refresh().catch(() => setError('No se pudo cargar este recurso.')); }, [resource]); async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const data: Record<string, unknown> = Object.fromEntries(form); if (resource === 'map') { data.latitude = Number(data.latitude); data.longitude = Number(data.longitude); } try { await apiRequest(`/api/admin/${resource}`, { method: 'POST', body: JSON.stringify(data) }); event.currentTarget.reset(); setNotice('Creado correctamente.'); await refresh(); } catch (e) { setError(message(e)); } } async function action(item: Item, action: 'publish' | 'unpublish' | 'delete') { if (action === 'delete' && !window.confirm('¿Eliminar este elemento? Dejará de estar disponible públicamente.')) return; try { await apiRequest(`/api/admin/${resource}/${item.id}${action === 'delete' ? '' : `/${action}`}`, { method: action === 'delete' ? 'DELETE' : 'POST', body: JSON.stringify({ version: item.version }) }); setNotice(action === 'delete' ? 'Eliminado correctamente.' : 'Actualizado correctamente.'); await refresh(); } catch (e) { setError(message(e)); } }
  return <section className="admin-page"><h1>{labels[resource]}</h1><form className="admin-form" onSubmit={create}><h2>Crear elemento</h2>{fields(resource).map(([name, label]) => <label key={name}>{label}<input name={name} required={name !== 'description' && name !== 'location'} type={name.includes('At') ? 'datetime-local' : name === 'latitude' || name === 'longitude' ? 'number' : 'text'} step={name === 'latitude' || name === 'longitude' ? 'any' : undefined} /></label>)}<button className="button primary">Crear</button></form>{notice && <p role="status">{notice}</p>}{error && <p role="alert">{error}</p>}{!items ? <p role="status">Cargando elementos…</p> : items.length === 0 ? <p>Aún no hay elementos.</p> : <ul className="admin-list">{items.map((item) => <li key={item.id}><strong>{String(item.title ?? item.label ?? item.contentKey)}</strong> <span>{item.state === 'published' ? 'Publicado' : 'Borrador'}</span><button onClick={() => void action(item, item.state === 'published' ? 'unpublish' : 'publish')}>{item.state === 'published' ? 'Despublicar' : 'Publicar'}</button><button className="danger" onClick={() => void action(item, 'delete')}>Eliminar</button></li>)}</ul>}</section>;
}
function message(error: unknown) { return (error as ApiError).status === 409 ? 'Este elemento cambió en otro lugar. Recargue e intente nuevamente.' : 'No se pudo completar la solicitud.'; }
type Participant = { id: string; fullName: string; email: string; phone?: string | null; militaryRank?: string | null; createdAt: string };
function ParticipantsPage() {
  const [items, setItems] = useState<Participant[]>(); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const refresh = () => apiRequest<{ participants: Participant[] }>('/api/admin/participants').then((d) => setItems(d.participants));
  useEffect(() => { void refresh().catch(() => setError('No se pudieron cargar los participantes.')); }, []);
  async function remove(p: Participant) {
    if (!window.confirm(`¿Eliminar a ${p.fullName} (${p.email})? Esta acción no se puede deshacer.`)) return;
    try { await apiRequest('/api/admin/participants/by-email', { method: 'DELETE', body: JSON.stringify({ email: p.email }) }); setNotice('Participante eliminado.'); await refresh(); } catch { setError('No se pudo eliminar el participante.'); }
  }
  return <section className="admin-page"><h1>Participantes{items ? ` (${items.length})` : ''}</h1>{notice && <p role="status">{notice}</p>}{error && <p role="alert">{error}</p>}
    {!items ? <p role="status">Cargando participantes…</p> : items.length === 0 ? <p>Aún no hay participantes registrados.</p> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Nombre</th><th>Email</th><th>Registro</th><th /></tr></thead><tbody>{items.map((p) => <tr key={p.id}><td>{p.fullName}</td><td>{p.email}</td><td>{new Date(p.createdAt).toLocaleString('es-AR')}</td><td><button className="danger" onClick={() => void remove(p)}>Eliminar</button></td></tr>)}</tbody></table></div>}</section>;
}
type Campaign = { id: string; state: string; audienceCount: number; createdAt: string; completedAt: string | null; delivered: number; pending: number; retrying: number; failed: number };
type Delivery = { id: string; recipientEmail: string; participantName: string; state: string; attempts: number; lastErrorCode: string | null };
const campaignStates: Record<string, string> = { queued: 'En cola', processing: 'Enviando', completed: 'Completada', completed_with_failures: 'Completada con fallas' };
const deliveryStates: Record<string, string> = { pending: 'Pendiente', processing: 'Enviando', delivered: 'Enviado', retryable_failed: 'Reintentando', terminal_failed: 'Fallido' };
function CampaignsPage() {
  const [campaigns, setCampaigns] = useState<Campaign[]>(); const [audience, setAudience] = useState<number>(); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const [open, setOpen] = useState<string>(); const [deliveries, setDeliveries] = useState<Delivery[]>();
  const refresh = () => Promise.all([apiRequest<{ campaigns: Campaign[] }>('/api/admin/diploma-campaigns'), apiRequest<{ participants: Participant[] }>('/api/admin/participants')]).then(([c, p]) => { setCampaigns(c.campaigns); setAudience(p.participants.length); });
  useEffect(() => { void refresh().catch(() => setError('No se pudieron cargar las campañas.')); }, []);
  const active = campaigns?.some((c) => c.state === 'queued' || c.state === 'processing');
  useEffect(() => { if (!active) return; const t = setInterval(() => { void refresh().catch(() => undefined); if (open) void loadDeliveries(open); }, 4000); return () => clearInterval(t); }, [active, open]);
  async function loadDeliveries(id: string) { const d = await apiRequest<{ deliveries: Delivery[] }>(`/api/admin/diploma-campaigns/${id}/deliveries`); setDeliveries(d.deliveries); }
  async function toggle(id: string) { if (open === id) { setOpen(undefined); return; } setOpen(id); setDeliveries(undefined); try { await loadDeliveries(id); } catch { setError('No se pudo cargar el detalle.'); } }
  async function launch() {
    if (!audience) { setError('No hay participantes registrados a quienes enviar.'); return; }
    if (!window.confirm(`Se enviará la salutación por email a ${audience} participante(s). ¿Confirmar el envío?`)) return;
    setBusy(true); setError(''); setNotice('');
    try { await apiRequest('/api/admin/diploma-campaigns', { method: 'POST', body: JSON.stringify({}) }); setNotice('Campaña lanzada. El envío comenzó en segundo plano.'); await refresh(); } catch { setError('No se pudo lanzar la campaña.'); } finally { setBusy(false); }
  }
  return <section className="admin-page"><h1>Campañas de salutación</h1>
    <div className="admin-form"><p>Cada campaña envía el diploma por email a <strong>todos</strong> los participantes registrados{audience !== undefined ? ` (${audience} actualmente)` : ''}.</p><button className="button primary" disabled={busy || !audience || active} onClick={() => void launch()}>{busy ? 'Lanzando…' : active ? 'Hay una campaña en curso' : 'Lanzar campaña'}</button></div>
    {notice && <p role="status">{notice}</p>}{error && <p role="alert">{error}</p>}
    {!campaigns ? <p role="status">Cargando campañas…</p> : campaigns.length === 0 ? <p>Aún no se lanzó ninguna campaña.</p> : <ul className="admin-list">{campaigns.map((c) => <li key={c.id} style={{ display: 'block' }}>
      <div style={{ display: 'flex', gap: '.75rem', flexWrap: 'wrap', alignItems: 'center' }}><strong>{new Date(c.createdAt).toLocaleString('es-AR')}</strong><span>{campaignStates[c.state] ?? c.state}</span><span>{c.delivered}/{c.audienceCount} enviados</span>{c.pending + c.retrying > 0 && <span>{c.pending + c.retrying} en curso</span>}{c.failed > 0 && <span className="danger">{c.failed} fallidos</span>}<button onClick={() => void toggle(c.id)}>{open === c.id ? 'Ocultar detalle' : 'Ver detalle'}</button></div>
      {open === c.id && (!deliveries ? <p role="status">Cargando detalle…</p> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Destinatario</th><th>Email</th><th>Estado</th><th>Intentos</th><th>Error</th></tr></thead><tbody>{deliveries.map((d) => <tr key={d.id}><td>{d.participantName}</td><td>{d.recipientEmail}</td><td>{deliveryStates[d.state] ?? d.state}</td><td>{d.attempts}</td><td>{d.lastErrorCode ?? '—'}</td></tr>)}</tbody></table></div>)}
    </li>)}</ul>}</section>;
}
export function AdminRoutes() { return <Routes><Route path="/admin/login" element={<AdminLogin />} /><Route element={<SessionGuard />}><Route path="/admin" element={<AdminShell />}><Route index element={<Dashboard />} /><Route path="content" element={<ResourcePage resource="content" />} /><Route path="schedule" element={<ResourcePage resource="schedule" />} /><Route path="map" element={<ResourcePage resource="map" />} /><Route path="participants" element={<ParticipantsPage />} /><Route path="campaigns" element={<CampaignsPage />} /></Route></Route></Routes>; }
